import { ReactNode } from "react";
import "./globals.css";
import { Bebas_Neue, Montserrat } from "next/font/google";
import type { Metadata } from "next";

const bebas = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bebas",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function GlobalLayout({
  children,
  params,
}: Readonly<{
  children: ReactNode;
  params: Promise<{ lang: string }>;
}>) {
  const { lang } = await params;

  return (
    <html lang={lang ?? "en"}>
      <body>
        <main
          className={`${bebas.variable} ${montserrat.variable} antialiased overflow-hidden`}
        >
          {children}
        </main>
      </body>
    </html>
  );
}
