import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { ReactNode } from "react";

const robotoSans = Roboto({
  variable: "--bebas-neue-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }: { children: ReactNode }) {
  return (
    <html lang={"en"}>
      <body className={`${robotoSans.variable} antialiased overflow-hidden`}>
        <main className={"dashboard_bg"}>{children}</main>;
      </body>
    </html>
  );
}
