import type { Metadata } from "next";
import { Bebas_Neue, Montserrat } from "next/font/google";
import { ReactNode } from "react";

const bebas = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bebas",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return <div className={`${bebas.variable} ${montserrat.variable} antialiased`}>{children}</div>;
}
